Feature/service worker
flare-app/client pull request #3
Opened 2017-07-25 18:56 UTC by julianweise

Implemented concept of background service worker for Response-View.
ServiceWorkerConecpt base on Googles idea of progressive web apps / serviceWorkerAPI.

2017-07-26 09:32 UTC, friedow requested changes

2017-07-26 09:32 UTC, friedow commented on public/bgSyncServiceWorker.js
> +const syncStore = {};
Only use global constants if you really need to.
When needed to use them, define them at the beginning of the file.

2017-07-26 09:32 UTC, friedow commented on public/bgSyncServiceWorker.js
> +	return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
What the hell?
Please provide a doc-string here.

2017-07-26 09:32 UTC, friedow commented on public/bgSyncServiceWorker.js
> +			headers: {
These parameters should be extracted to a constant to increase the readability.

2017-07-26 09:32 UTC, friedow commented on public/bgSyncServiceWorker.js
> +			headers: {
Plus, you use them twice.

2017-07-26 09:32 UTC, friedow commented on src/Login/Login.js
> +	onSubmitLogin(event) {
Rename this to "handleSubmitLogin".

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +	constructor(props) {
You don't need the props here.

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +	onSubmitMistake() {
Rename this to "handleSubmitMistake".

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +	onSubmitResponse(willAppear, transportation) {
Rename this to "handleSubmitResponse".

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +				authToke: this.props.authToken,
Character missing "authTokeN"

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +				authToke: this.props.authToken,
Character missing "authTokeN"

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +			}.bind(this));
Please bind "this" in the constructor.

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +		this.state = {dataSended: false};
Grammar mistake: 

VERB | to send | sent | sent

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +		navigator.serviceWorker.ready.then(function() {
Please use lambda functions like this () => {}.

2017-07-26 09:32 UTC, friedow commented on src/Response/Response.js
> +			navigator.geolocation.getCurrentPosition(function (position) {
Please use lambda functions like this () => {}.

2017-07-26 09:32 UTC, friedow commented on src/App.js
> +			}, function(err) {
Please use lambda functions like this () => {}.

2017-07-26 09:32 UTC, friedow commented on src/App.js
> +			navigator.serviceWorker.register(swUrl, {scope: '/'}).then(function(registration) {
Please use lambda functions like this () => {}.

2017-07-26 09:32 UTC, friedow commented on src/config/config-template,js.js
> +	backendAPIRoute: 'http://<ip>:<port>/api/user/'
Please use "https://flare-resq.de/api/user" as default route.

2017-07-29 10:56 UTC, julianweise commented on src/Response/Response.js
> +	constructor(props) {
I need them to call super properly

2017-07-29 10:58 UTC, julianweise commented on src/Response/Response.js
> +		this.state = {dataSended: false};
Shame on me :/

2017-07-29 11:03 UTC, julianweise commented on src/Response/Response.js
> +			}.bind(this));
Using arrow-lambda functions as suggested before obviates binding this context

2017-07-29 11:04 UTC, julianweise commented on src/Response/Response.js
> +		navigator.serviceWorker.ready.then(function() {
Not necessary - this context is not required

2017-07-29 11:05 UTC, julianweise commented on src/App.js
> +			navigator.serviceWorker.register(swUrl, {scope: '/'}).then(function(registration) {
Not necessary - this context is not required

2017-08-02 15:59 UTC, friedow approved these changes

2017-08-03 15:43 UTC, merged